name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - "main"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: |
          npm install
          npm list  # Show installed packages
      
      - name: Build
        run: |
          pwd  # Show current directory
          ls -la  # List all files
          npm run build
          echo "Build completed"
          ls -la docs  # Check docs directory
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true  # Automatically remove deleted files from the deploy branch 